Ini, TOML

# Conteúdo do arquivo .streamlit/secrets.toml
# Este é o URL completo da Planilha OncoFlux_Database
SHEET_URL = "O URL COMPLETO DA SUA PLANILHA COPIADO DO NAVEGADOR"

# Este é todo o conteúdo do arquivo JSON que você baixou.
# Cole TUDO, incluindo as chaves e os valores, entre as três aspas duplas (""").
google_sheets_creds = """
{
    "type": "service_account",
    "project_id": "SEU_ID_DO_PROJETO",
    "private_key_id": "SUA_CHAVE_PRIVADA_ID",
    "private_key": "-----BEGIN PRIVATE KEY-----SEU_SEGREDO_AQUI-----END PRIVATE KEY-----\n",
    "client_email": "SEU_EMAIL@appspot.gserviceaccount.com",
    "client_id": "SEU_CLIENT_ID",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/SEU_EMAIL.iam.gserviceaccount.com"
}
"""
